language: node_js
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run copy-secrets
  - npm test
  # - npm run build
branches:
  only: # Only build master and EDSC-2133. All pull requests also get built
    - master
    - EDSC-2133
deploy:
  provider: script
  script: bin/ecc-sync
  on:
    branch: master
    repo: nasa/earthdata-search
